### ISSUE TITLE
Unable to access functions in retained-navigation

### ISSUE THREAD

**Issue by saket** [marcellogalhardo/retained#66]
Thanks for creating this library! I'm trying to use it in Compose UI, but I'm unable to access `NavBackStackEntry.retain` from my project. It's almost as if Gradle is unable to find any of its APIs. This can be reproduced in the sample project too!

```diff
- implementation projects.core
- implementation projects.activity
- implementation projects.fragment
- implementation projects.view

+ implementation 'dev.marcellogalhardo:retained-activity:0.15.0'
+ implementation 'dev.marcellogalhardo:retained-fragment:0.15.0'
+ implementation 'dev.marcellogalhardo:retained-view:0.15.0'
+ implementation 'dev.marcellogalhardo:retained-navigation:0.15.0'
```

Both `SampleFragment` and `SampleView` will fail to compile. Any ideas what might be happening?

**Comment by saket** [comment]
In-IDE navigation to `retain` functions don't work either: 
<img width="739" alt="image" src="https://user-images.githubusercontent.com/2387680/164589071-f28bbde0-febe-43f4-ac01-6bc07ad593bb.png">

**Comment by marcellogalhardo** [comment]
Hey @saket - thank you for reporting the problem!

It looks like there is a problem with the `view` and `fragment` artifacts published to Maven Central for version `0.15.0`. I tried to build the artifact locally and import it manually, and it looks like everything is the right in place.

For now, as a workaround, you can use version `0.14.1` to unblock you.

I will investigate a little more from my side locally, and in the meantime, I will trigger a new release to ensure we did not have a problem with the publishing pipeline.

**Comment by marcellogalhardo** [comment]
Hey @saket - thank you for reporting the problem with so many details!

It looks like there is a problem with the `view` and `fragment` artifacts published to Maven Central for version `0.15.0`. I built it locally and everything looks right. That is a bit confusing.

For now, as a workaround, you can use version `0.14.0` to unblock you.

I will investigate from my side and I will keep you posted.

**Comment by marcellogalhardo** [comment]
Hey @saket -  I released a new version with a fix for this problem. Please, check version `0.15.3` and let me know if you experience any problems.

Thank you!

**Comment by saket** [comment]
Yep `0.15.3` works. Thanks @marcellogalhardo!
